### PR TITLE
Improve GitHub Actions

### PR DESCRIPTION
**Pull request by KTibow**
I recently announced ha-blueprint:
- With formatting (black + isort for python, prettier for js)
  - It’ll go ahead and pull it, format it, and amend the changes to the last commit.
- With lint
  - JS: Run ESLint to catch syntax errors
  - Python: It runs Hassfest (to catch invalid integrations), HACS (to catch invalid HACS integrations), and flake8 (to catch invalid python).

https://community.home-assistant.io/t/made-a-custom-integration-or-card-ive-created-an-all-in-one-github-action-for-you/235041
This makes it so it auto-checks for HACS, hassfest, and flake8 so you won't have to worry about it being invalid.

### CODE REVIEW

**Comment by KTibow** [comment]
Mind pulling this in @crowbarz?

**Comment by crowbarz** [comment]
@KTibow on initial review this looks like a worthwhile effort, though I think it's prudent to perform some due diligence first. I note that you really do mean "recent" in a literal sense (9 days ago!) so I have a few questions to help me better understand the goals of your code and evaluate whether to move to it from the hassfest GitHub action currently in use and endorsed by balloob:

- Has your code been peer reviewed and/or tested by the Home Assistant community already?
- Can you point me to the overall strategy for CI in Home Assistant where this code fits in, if there is one? I want to understand the bigger picture here.

Thanks.

**Comment by KTibow** [comment]
1. Yes, here you go: https://github.com/search?q=ha-blueprint+-user%3AKTibow&type=code
2. Could you clarify a bit? Basically it shows an error when you push a commit that makes the Python invalid or Hassfest invalid. It can also provide you with some tips on improving your code, from wemake-python-styleguide and flake8.

**Comment by crowbarz** [comment]
To clarify my second question, I wanted to know if your future plan for this action was to get it adopted by the HACS or HA code owners as a standard requirement for new integrations submitted into HACS and/or HA core.

After reviewing the action in more depth, I have some more questions/comments:

* Is your repository in essence a fork of [custom-components/blueprint](https://github.com/custom-components/blueprint) with an additional GitHub action defined? I can't figure out how `custom_integration/blueprint` is used by the action, and the README implies the main purpose of the repository is a home for the action rather than a replacement blueprint.
* If I disable formatting by setting `FORMAT_CODE` to `DISABLED` per the README, then how do I also avoid passing a GITHUB_TOKEN to the action as well? The [permissions for the automatically created GITHUB_TOKEN](https://docs.github.com/en/free-pro-team@latest/actions/reference/authentication-in-a-workflow#permissions-for-the-github_token) are too broad for this action in this case, as there is no need for read/write access to the repository if formatting isn't enabled.
* FYI I will need to pin this action to a commit SHA (such as the one for the initial release KTibow/ha-blueprint@81c7fc3097f47c704b2324dc705d5a8198278dfa) per [GitHub security guidance for third-party actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions).

**Comment by KTibow** [comment]
I don't have this plan. I just wanted to make something that anybody could use. I currently have pending PRs to add a link to the HACS GitHub Actions doc in the hacs/default PR template, and to add ha-blueprint in the tip box for the HACS GitHub Actions doc. I have no plans to do anything for the core, they already have their own set of rules which I based mine off of.

- I use it to make sure that it works. If I make a change that makes it fail on valid code, it automatically sends me a GitHub notification.
- Thanks for letting me know that you're careful about security! I'll go ahead and mark it as not required.
- Okay. I get it. If you want, you can watch the repo to get a notification when I make a PR from unstable to stable.

**Pull request closed without merging**
